<?php
declare(strict_types=1);

// LongevityCompetition SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

LongevityCompetitionUtility::setRegistrar(function (LongevityCompetitionUtility $u): void {
    $u->clean = [LongevityCompetitionClean::class, 'call'];
    $u->done = [LongevityCompetitionDone::class, 'call'];
    $u->make_error = [LongevityCompetitionMakeError::class, 'call'];
    $u->feature_add = [LongevityCompetitionFeatureAdd::class, 'call'];
    $u->feature_hook = [LongevityCompetitionFeatureHook::class, 'call'];
    $u->feature_init = [LongevityCompetitionFeatureInit::class, 'call'];
    $u->fetcher = [LongevityCompetitionFetcher::class, 'call'];
    $u->make_fetch_def = [LongevityCompetitionMakeFetchDef::class, 'call'];
    $u->make_context = [LongevityCompetitionMakeContext::class, 'call'];
    $u->make_options = [LongevityCompetitionMakeOptions::class, 'call'];
    $u->make_request = [LongevityCompetitionMakeRequest::class, 'call'];
    $u->make_response = [LongevityCompetitionMakeResponse::class, 'call'];
    $u->make_result = [LongevityCompetitionMakeResult::class, 'call'];
    $u->make_point = [LongevityCompetitionMakePoint::class, 'call'];
    $u->make_spec = [LongevityCompetitionMakeSpec::class, 'call'];
    $u->make_url = [LongevityCompetitionMakeUrl::class, 'call'];
    $u->param = [LongevityCompetitionParam::class, 'call'];
    $u->prepare_auth = [LongevityCompetitionPrepareAuth::class, 'call'];
    $u->prepare_body = [LongevityCompetitionPrepareBody::class, 'call'];
    $u->prepare_headers = [LongevityCompetitionPrepareHeaders::class, 'call'];
    $u->prepare_method = [LongevityCompetitionPrepareMethod::class, 'call'];
    $u->prepare_params = [LongevityCompetitionPrepareParams::class, 'call'];
    $u->prepare_path = [LongevityCompetitionPreparePath::class, 'call'];
    $u->prepare_query = [LongevityCompetitionPrepareQuery::class, 'call'];
    $u->graphql_body = [LongevityCompetitionGraphql::class, 'body'];
    $u->graphql_errors = [LongevityCompetitionGraphql::class, 'errors'];
    $u->result_basic = [LongevityCompetitionResultBasic::class, 'call'];
    $u->result_body = [LongevityCompetitionResultBody::class, 'call'];
    $u->result_headers = [LongevityCompetitionResultHeaders::class, 'call'];
    $u->transform_request = [LongevityCompetitionTransformRequest::class, 'call'];
    $u->transform_response = [LongevityCompetitionTransformResponse::class, 'call'];
});
